/* Generated by scripts/build-design-system.js from tokens/tokens.json. Do not edit. */
/* token-source-sha256: 43ac5c34303be438dd18475434af5c36b6ba3b997aba992d064148b4b6f0c5e4 */
window.RMDS_TOKENS = {
  "color": {
    "brand": [
      {
        "label": "Primary · Teal",
        "group": "primary",
        "base": "600",
        "note": "Brand base · light-mode accent"
      },
      {
        "label": "Secondary · Amber",
        "group": "secondary",
        "base": "500",
        "note": "Highlights & attention"
      }
    ],
    "primary": [
      [
        "50",
        "#e6f6f6",
        null
      ],
      [
        "100",
        "#c4e9e9",
        null
      ],
      [
        "200",
        "#9ad9da",
        null
      ],
      [
        "300",
        "#6cc8c9",
        null
      ],
      [
        "400",
        "#45bbbb",
        null
      ],
      [
        "500",
        "#24a7a9",
        null
      ],
      [
        "600",
        "#0d7377",
        "brand base · light-mode accent"
      ],
      [
        "700",
        "#0b6165",
        null
      ],
      [
        "800",
        "#094e51",
        null
      ],
      [
        "900",
        "#073b3e",
        null
      ]
    ],
    "secondary": [
      [
        "50",
        "#fff8e8",
        null
      ],
      [
        "100",
        "#ffecc0",
        null
      ],
      [
        "200",
        "#ffdc8d",
        null
      ],
      [
        "300",
        "#ffcc5c",
        null
      ],
      [
        "400",
        "#ffbe38",
        null
      ],
      [
        "500",
        "#ffac2e",
        "brand base"
      ],
      [
        "600",
        "#e08f14",
        null
      ],
      [
        "700",
        "#b8730e",
        null
      ],
      [
        "800",
        "#8f580b",
        null
      ],
      [
        "900",
        "#663e07",
        null
      ]
    ],
    "neutral": [
      [
        "0",
        "#ffffff",
        "pure white"
      ],
      [
        "50",
        "#fafbfc",
        null
      ],
      [
        "100",
        "#f1f3f8",
        "light background"
      ],
      [
        "200",
        "#e6e9ef",
        null
      ],
      [
        "300",
        "#cdd2dc",
        null
      ],
      [
        "400",
        "#9aa1af",
        null
      ],
      [
        "500",
        "#6b7280",
        null
      ],
      [
        "600",
        "#4b5261",
        null
      ],
      [
        "700",
        "#333a47",
        null
      ],
      [
        "800",
        "#1d2129",
        null
      ],
      [
        "900",
        "#151616",
        "dark background"
      ]
    ],
    "semantic": [
      {
        "name": "Success",
        "light": "#1cad59",
        "dark": "#00e676",
        "role": "positive / confirm states",
        "usage": "positive / confirm states"
      },
      {
        "name": "Warning",
        "light": "#dca500",
        "dark": "#ffd505",
        "role": "caution / pending states",
        "usage": "caution / pending states"
      },
      {
        "name": "Danger",
        "light": "#ff4b4b",
        "dark": "#ff6a6a",
        "role": "errors / destructive actions",
        "usage": "errors / destructive actions"
      },
      {
        "name": "Info",
        "light": "#0d7377",
        "dark": "#32e0c4",
        "role": "information / neutral feedback",
        "usage": "information / neutral feedback"
      }
    ],
    "theme": [
      {
        "name": "Text",
        "light": "#141414",
        "dark": "#dcdcdc",
        "role": "default text",
        "usage": "default text"
      },
      {
        "name": "Foreground",
        "light": "#fcfdff",
        "dark": "#1b1c1d",
        "role": "surface / elevated backgrounds",
        "usage": "surface / elevated backgrounds"
      },
      {
        "name": "Background",
        "light": "#f1f3f8",
        "dark": "#151616",
        "role": "page background",
        "usage": "page background"
      },
      {
        "name": "Accent",
        "light": "#0d7377",
        "dark": "#32e0c4",
        "role": "active / interactive states",
        "usage": "active / interactive states"
      },
      {
        "name": "Secondary",
        "light": "#ffac2e",
        "dark": "#d60739",
        "role": "highlight / attention",
        "usage": "highlight / attention"
      },
      {
        "name": "Danger",
        "light": "#ff4b4b",
        "dark": "#ff6a6a",
        "role": "errors / destructive actions",
        "usage": "errors / destructive actions"
      }
    ]
  },
  "type": {
    "families": [
      {
        "name": "Poppins",
        "token": "--font-display",
        "stack": "\"Poppins\", sans-serif",
        "usage": "Headings, display text, brand moments"
      },
      {
        "name": "Roboto",
        "token": "--font-body",
        "stack": "\"Roboto\", sans-serif",
        "usage": "Body copy, UI text, long-form content"
      },
      {
        "name": "Roboto Mono",
        "token": "--font-mono",
        "stack": "\"Roboto Mono\", monospace",
        "usage": "Code, numbers, data, tokens"
      }
    ],
    "scale": [
      {
        "name": "Display",
        "size": "clamp(2.5rem, 5vw, 3.5rem)",
        "weight": 700,
        "lineHeight": 1.15,
        "family": "display",
        "lh": 1.15,
        "sample": "The design system"
      },
      {
        "name": "H1",
        "size": "2.5rem",
        "weight": 700,
        "lineHeight": 1.2,
        "family": "display",
        "lh": 1.2,
        "sample": "Almost before we knew it"
      },
      {
        "name": "H2",
        "size": "2rem",
        "weight": 700,
        "lineHeight": 1.25,
        "family": "display",
        "lh": 1.25,
        "sample": "Building on primitives"
      },
      {
        "name": "H3",
        "size": "1.4rem",
        "weight": 600,
        "lineHeight": 1.3,
        "family": "display",
        "lh": 1.3,
        "sample": "Components, not pages"
      },
      {
        "name": "H4",
        "size": "1rem",
        "weight": 600,
        "lineHeight": 1.4,
        "family": "display",
        "lh": 1.4,
        "sample": "Section heading"
      },
      {
        "name": "H5",
        "size": "0.8rem",
        "weight": 500,
        "lineHeight": 1.5,
        "family": "display",
        "transform": "uppercase",
        "tracking": "0.08em",
        "lh": 1.5,
        "sample": "Overline label"
      },
      {
        "name": "BODY",
        "size": "0.9rem",
        "weight": 400,
        "lineHeight": 1.7,
        "family": "body",
        "lh": 1.7,
        "sample": "The quick brown fox jumps over the lazy dog and keeps on going to test the line length comfortably."
      },
      {
        "name": "SMALL",
        "size": "0.75rem",
        "weight": 400,
        "lineHeight": 1.6,
        "family": "body",
        "lh": 1.6,
        "sample": "Helper text and captions"
      },
      {
        "name": "MONO",
        "size": "0.875rem",
        "weight": 400,
        "lineHeight": 1.6,
        "family": "mono",
        "lh": 1.6,
        "sample": "0x8F 12,480,000 tokens"
      }
    ]
  },
  "spacing": [
    {
      "name": "space-1",
      "rem": "0.25rem",
      "px": 4,
      "usage": "tight grouping, icon gaps"
    },
    {
      "name": "space-2",
      "rem": "0.5rem",
      "px": 8,
      "usage": "component internal padding"
    },
    {
      "name": "space-3",
      "rem": "0.75rem",
      "px": 12,
      "usage": "compact list / form gaps"
    },
    {
      "name": "space-4",
      "rem": "1rem",
      "px": 16,
      "usage": "default gutters, card padding"
    },
    {
      "name": "space-5",
      "rem": "1.5rem",
      "px": 24,
      "usage": "section spacing, popup padding"
    },
    {
      "name": "space-6",
      "rem": "2rem",
      "px": 32,
      "usage": "large card / panel gaps"
    },
    {
      "name": "space-7",
      "rem": "3rem",
      "px": 48,
      "usage": "section rhythm"
    },
    {
      "name": "space-8",
      "rem": "4rem",
      "px": 64,
      "usage": "page-level rhythm"
    },
    {
      "name": "space-9",
      "rem": "6rem",
      "px": 96,
      "usage": "hero / landing spacing"
    }
  ],
  "radius": [
    {
      "name": "sm",
      "value": "0.2rem",
      "usage": "chips, tags, small highlights"
    },
    {
      "name": "md",
      "value": "0.3rem",
      "usage": "default component radius (buttons, inputs)"
    },
    {
      "name": "lg",
      "value": "0.4rem",
      "usage": "cards, popups, larger surfaces"
    },
    {
      "name": "full",
      "value": "9999px",
      "usage": "pills, avatars, toggle handles"
    }
  ],
  "shadow": [
    {
      "name": "sm",
      "value": "0 1px 2px rgba(20,20,20,0.06)",
      "usage": "subtle separation, cards"
    },
    {
      "name": "md",
      "value": "0 2px 8px rgba(20,20,20,0.12)",
      "usage": "popups, floating action elements"
    },
    {
      "name": "lg",
      "value": "0 8px 24px rgba(20,20,20,0.16)",
      "usage": "modals, dropdown menus, elevated surfaces"
    }
  ],
  "motion": {
    "duration": [
      {
        "name": "fast",
        "ms": 100,
        "usage": "micro-interactions, hovers, ripples"
      },
      {
        "name": "base",
        "ms": 150,
        "usage": "default UI transitions"
      },
      {
        "name": "slow",
        "ms": 300,
        "usage": "page changes, popup show/hide, view transitions"
      }
    ],
    "easing": [
      {
        "name": "linear",
        "value": "linear",
        "usage": "Default browser curve, safe fallback"
      },
      {
        "name": "ease",
        "value": "ease",
        "usage": "Default browser curve, safe fallback"
      },
      {
        "name": "ease-out",
        "value": "ease-out",
        "usage": "Elements leaving the screen, standard"
      },
      {
        "name": "spring",
        "value": "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        "usage": "Delightful entrances, popups"
      }
    ]
  },
  "breakpoints": [
    {
      "name": "Mobile",
      "range": "0px – 639px",
      "usage": "phones, single column"
    },
    {
      "name": "Tablet",
      "range": "640px – 1023px",
      "usage": "foldables, small tablets"
    },
    {
      "name": "Desktop",
      "range": "≥ 1024px",
      "usage": "laptops & desktops"
    }
  ],
  "zIndex": [
    {
      "name": "Base",
      "value": 1,
      "usage": "Default content"
    },
    {
      "name": "Header",
      "value": 10,
      "usage": "App header / sticky bars"
    },
    {
      "name": "Popup Stack",
      "value": 50,
      "usage": "Modals & popups (increments per open)"
    },
    {
      "name": "Notification",
      "value": 100,
      "usage": "Toast drawer"
    }
  ]
};
